## Imports

In [5]:
from bs4 import BeautifulSoup
from time import sleep

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC

from tqdm import tqdm

import pandas as pd
from geopy import geocoders
import requests
import re

## Selenium Setup

In [6]:
def openChrome():
    portz = 9995
    chromeOptions = webdriver.ChromeOptions()
    chromeOptions.add_argument(f'--remote-debugging-port={portz}')
    chromeOptions.add_experimental_option("excludeSwitches", ["enable-automation"])
    chromeOptions.add_argument("--disable-blink-features=AutomationControlled")
    chromeOptions.add_argument("--disable-blink-features")
    # chromeOptions.add_argument("--headless")

    prefs = {"profile.managed_default_content_settings.images": 2}
    chromeOptions.add_experimental_option("prefs", prefs)

    driver = webdriver.Chrome(executable_path=r"C:\Users\kylew\OneDrive\Desktop\Advent\chromedriver.exe", options=chromeOptions)    
    driver.set_window_rect(0, 0, width=360, height=600)
    driver.set_page_load_timeout(66)
    return driver

## Scraper Code

In [7]:
# On the new tab that opens - login to RCA
# Move over to the transactions tab and pull up the table view (3 lines)
# Hit the enter key on the code below and the scrape will start

In [ ]:
driver = openChrome()
list_write = []

url =  f'https://app.rcanalytics.com/home'
driver.get(url)
sleep(1)
input("Login Select And Enter Continue")

driver.set_window_rect(0, 0, width=1222, height=999)

output_file_path = 'rca_transactions.xlsx'
with pd.ExcelWriter(output_file_path, engine='xlsxwriter') as writer:
    pass

list_pname = []
while 1:
    page_source  = driver.page_source
    soup = BeautifulSoup(page_source, 'html.parser')
    data = soup.find_all("tr",attrs={"ng-click": "pinTransactionsTableController.onSelectTransactionRow(row.data.transaction);"})
    stt_nb = 1
    for item in data:
        stt_text, date_s, p_type = "", "", ""
        transaction = item.find("td", class_="transaction")
        transaction = transaction.find_all("span", attrs={"tooltip-placement": "top-left"})
        if transaction != None:
            stt_text = transaction[0].text
            date_s = transaction[1].text
            p_type = transaction[2].text

        p_name, address_1, address_2 = "", "", ""
        address_list = item.find("td", class_="address")
        pname = address_list.find("a", attrs={"target": "_blank"})
        link_s = pname.get("href")
        p_name = pname.text

        address_list = address_list.find_all("span", attrs={"tooltip-placement": "top-left"})
        try:
            address_1 = address_list[1].text
        except:
            address_1 = ""
        try:
            address_2 = address_list[2].text
        except:
            address_2 = ""
        address = address_1 + " " + address_2
        if p_name not in list_pname:
            list_pname.append(p_name)
            stt_nb += 1

            sf, year_blt, flrs = "", "", ""
            info = item.find("td", class_="propertyInfo")
            info = info.find_all("span", attrs={"tooltip-placement": "top-left"})
            try:
                sf = info[0].text
            except:
                sf = ""
            try:
                year_blt = info[1].text
            except:
                year_blt = ""
            try:
                flrs = info[2].text
            except:
                flrs = ""

            price, sf_unit, cap = "", "", ""
            i_price = item.find("td", class_="transactionPrice")
            i_price = i_price.find_all("span", attrs={"tooltip-placement": "top-left"})
            if i_price != None:
                for pc in i_price:
                    t_pc = pc.text
                    if "sf" in t_pc or "unit" in t_pc:
                        sf_unit = t_pc
                    elif "confm'd" in t_pc or "approx" in t_pc:
                        price = t_pc
                    else:
                        cap = t_pc

            buyer, seller, ledder = "", "", ""
            entities = item.find("td", class_="entities")
            entities = entities.find_all("div", attrs={"ng-repeat": "item in row.data.transaction.PlayersFormatted"})
            for en in entities:
                img_buy = en.find("img", attrs={"src": "/assets/images/bsb/icon_owner.svg"})
                if img_buy != None:
                    buyer = img_buy.find_next("span").text

                img_sell = en.find("img", attrs={"src": "/assets/images/bsb/icon_seller.svg"})
                if img_sell != None:
                    seller = img_sell.find_next("span").text

                img_led = en.find("img", attrs={"src": "/assets/images/bsb/icon_lender.svg"})
                if img_led != None:
                    ledder = img_led.find_next("span").text

            comments = ""
            comments = item.find("td", class_="comments")
            if comments != None:
                comments = comments.text

            list_write = []
            list_write.append([stt_text, date_s, p_type, p_name, address, sf, year_blt, flrs,  price, sf_unit, cap, buyer, seller, ledder, comments])
            rows = list(zip(*list_write))
            cols_names = ['Transaction Type', 'Transaction Date', 'Property Type', 'Property Name', 'Address', 'SF / Units', 'Year Blt/Reno', '#Buildings/Flrs', 'Price', '$/SF/Units', 'Cap Rate', 'Owner/Buyer', 'Seller', 'Lender', 'Comments']
            df_new_rows = pd.DataFrame(dict(zip(cols_names, rows)))

            df_existing = pd.read_excel(output_file_path)
            df_combined = pd.concat([df_existing, df_new_rows], ignore_index=True)
            df_combined.to_excel(output_file_path, index=False)

    kkk = 1
    while 1:
        try:
            element = WebDriverWait(driver,0.1).until(
                EC.presence_of_element_located((By.XPATH, f"(//tr[@ng-click='pinTransactionsTableController.onSelectTransactionRow(row.data.transaction);'])[{kkk}]"))
            )
        except:
            driver.execute_script("arguments[0].scrollIntoView();", element) 
            break
        kkk += 1

input("Done")

## Add Latitude and Longitude

In [4]:
df = pd.read_excel(r"C:\Users\kylew\OneDrive\Desktop\MLSA\Scripts\rca.xlsx")
df

,Transaction Type,Transaction Date,Property Type,Property Name,Address,SF / Units,Year Blt/Reno,#Buildings/Flrs,Price,$/SF/Units,Cap Rate,Owner/Buyer,Seller,Lender,Comments
0,Refinance,Sep '23,Industrial,1000 North Highway 77,"1000 North Hwy 77 Hillsboro, TX 76645 USA","117,060 sf",,NaN,NaN,NaN,,Joseph Ravitsky,NaN,NewtekOne,Warehouse property;
1,Refinance,Nov '23,Industrial,1001 Webster Avenue,"1001 Webster Ave Waco, TX 76706 USA","54,294 sf",1898,1 bldg/1 flr,NaN,NaN,,Ryan Gibson,NaN,Independent Financial,Warehouse property; buyer assumed mtg; prior s...
2,Sale,Nov '23,Industrial,101 North Highway 146,"101 N Hwy 146 Texas City, TX 77590 USA","36,500 sf",1972/2022,NaN,NaN,NaN,private,Benito X Valadez,TJC Captial Management LLC,NaN,Warehouse/mfg property;
3,Sale,Nov '23,Industrial,10130 West Gulf Bank Road,"10130 W Gulf Bank Rd Houston, TX 77040 USA","34,482 sf",1980,1 bldg/1 flr,NaN,NaN,,Russell W Griffin,10130 West Gulf Bank-2019 LP,Texas Security Bank,Warehouse property; prior sale: Oct-19;
4,Sale,Oct '23,Industrial,10355 Deer Trail Dr,"10355 Deer Trail Dr Houston, TX 77038 USA","62,255 sf",,NaN,$8.4 confm'd,$135 /sf,,Interglass Corp,Rycore Capital,NaN,Warehouse property;
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401,Construction,Nov '23,Industrial,Waxahachie,"I-35 Midlothian, TX 76065 USA",NaN,Underway,4 bldgs,NaN,NaN,,Blue Star Investments,NaN,NaN,Est Completion: Q4 2024; Warehouse property;
402,Construction,Oct '23,Industrial,WC T Project Warehouse,"1530 FM973 Taylor, TX 76574 USA","70,000 sf",Underway,1 bldg/1 flr,NaN,NaN,,Samsung Group,NaN,NaN,Est Completion: Q4 2024; Warehouse/distributio...
403,Construction,Oct '23,Industrial,West Loop Business Park,"724 Jim Wright Fwy White Settlement, TX 76108...","140,000 sf",Underway,14 bldgs/1 flr,NaN,NaN,,Street Realty,NaN,FirstBank Southwest,Est Completion: Q4 2024; Flex property; prior ...
404,Sale,Nov '23,Hotel,Whitten Inn Cotulla RV Park,"145 FM468 Cotulla, TX 78014 USA",60 units,2015,2 bldgs/2 flrs,NaN,NaN,,Areli P Villa,Super 5 LLC,Woori Financial,Limited Service property; prior sale: Aug-17;
405,Sale,Oct '23,Industrial,Woodlands Design Center,"30643 FM2978 Magnolia, TX 77354 USA","9,028 sf",2016,3 bldgs/1 flr,NaN,NaN,,Jose a L Solorio,Justin Tipler,Mint National Bank,"Warehouse/showroom property; Tenants: Tipler, ..."

In [5]:
geolocator = geocoders.GoogleV3(api_key='AIzaSyBM9LfiT56LWHu73cOpTwpiB_wBEbncqWg')

In [6]:
latitude = []
longitude = []

with tqdm(total=len(df)) as pbar:
    for index, row in df.iterrows():
        url = str(row['Address'])
        try:
            location = geolocator.geocode(url)
            latitude.append(location.latitude)
            longitude.append(location.longitude)
        except: 
            print("Error finding latitude/longitude for: ", row['Address'])
            latitude.append('')
            longitude.append('')
            
        pbar.update(1)

100%|██████████| 406/406 [01:09<00:00,  5.87it/s]

In [7]:
df['latitude'] = latitude
df['longitude'] = longitude
df

,Transaction Type,Transaction Date,Property Type,Property Name,Address,SF / Units,Year Blt/Reno,#Buildings/Flrs,Price,$/SF/Units,Cap Rate,Owner/Buyer,Seller,Lender,Comments,latitude,longitude
0,Refinance,Sep '23,Industrial,1000 North Highway 77,"1000 North Hwy 77 Hillsboro, TX 76645 USA","117,060 sf",,NaN,NaN,NaN,,Joseph Ravitsky,NaN,NewtekOne,Warehouse property;,32.024201,-97.124076
1,Refinance,Nov '23,Industrial,1001 Webster Avenue,"1001 Webster Ave Waco, TX 76706 USA","54,294 sf",1898,1 bldg/1 flr,NaN,NaN,,Ryan Gibson,NaN,Independent Financial,Warehouse property; buyer assumed mtg; prior s...,31.549477,-97.133010
2,Sale,Nov '23,Industrial,101 North Highway 146,"101 N Hwy 146 Texas City, TX 77590 USA","36,500 sf",1972/2022,NaN,NaN,NaN,private,Benito X Valadez,TJC Captial Management LLC,NaN,Warehouse/mfg property;,29.384906,-94.951894
3,Sale,Nov '23,Industrial,10130 West Gulf Bank Road,"10130 W Gulf Bank Rd Houston, TX 77040 USA","34,482 sf",1980,1 bldg/1 flr,NaN,NaN,,Russell W Griffin,10130 West Gulf Bank-2019 LP,Texas Security Bank,Warehouse property; prior sale: Oct-19;,29.879761,-95.550172
4,Sale,Oct '23,Industrial,10355 Deer Trail Dr,"10355 Deer Trail Dr Houston, TX 77038 USA","62,255 sf",,NaN,$8.4 confm'd,$135 /sf,,Interglass Corp,Rycore Capital,NaN,Warehouse property;,29.917470,-95.424172
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401,Construction,Nov '23,Industrial,Waxahachie,"I-35 Midlothian, TX 76065 USA",NaN,Underway,4 bldgs,NaN,NaN,,Blue Star Investments,NaN,NaN,Est Completion: Q4 2024; Warehouse property;,31.967535,-97.119490
402,Construction,Oct '23,Industrial,WC T Project Warehouse,"1530 FM973 Taylor, TX 76574 USA","70,000 sf",Underway,1 bldg/1 flr,NaN,NaN,,Samsung Group,NaN,NaN,Est Completion: Q4 2024; Warehouse/distributio...,30.532934,-97.446720
403,Construction,Oct '23,Industrial,West Loop Business Park,"724 Jim Wright Fwy White Settlement, TX 76108...","140,000 sf",Underway,14 bldgs/1 flr,NaN,NaN,,Street Realty,NaN,FirstBank Southwest,Est Completion: Q4 2024; Flex property; prior ...,32.771636,-97.474398
404,Sale,Nov '23,Hotel,Whitten Inn Cotulla RV Park,"145 FM468 Cotulla, TX 78014 USA",60 units,2015,2 bldgs/2 flrs,NaN,NaN,,Areli P Villa,Super 5 LLC,Woori Financial,Limited Service property; prior sale: Aug-17;,28.444958,-99.251926
405,Sale,Oct '23,Industrial,Woodlands Design Center,"30643 FM2978 Magnolia, TX 77354 USA","9,028 sf",2016,3 bldgs/1 flr,NaN,NaN,,Jose a L Solorio,Justin Tipler,Mint National Bank,"Warehouse/showroom property; Tenants: Tipler, ...",30.196429,-95.588027

In [8]:
df.to_csv(r"C:\Users\kylew\OneDrive\Desktop\MLSA\Scripts\RCA_Scrape.csv", index=False)

# Ali's Code

In [ ]:
import requests
import json
import pandas as pd

url = "https://app.rcanalytics.com/api/v1/propertySearch/search"

payload = {
  "RequestType": 0,
  "MapBounds": {
    "northeast": {
      "latitude": 73.92246884621464,
      "longitude": 109.3359375
    },
    "southwest": {
      "latitude": -73.92246884621464,
      "longitude": -109.3359375
    }
  },
  "CenterPoint": {
    "latitude": None,
    "longitude": None
  },
  "MapZoom": 2,
  "SortOrder": {
    "Field": "StatusDate",
    "Desc": True
  },
  "IncludePins": True,
  "IncludeBubbles": False,
  "SearchGeoShape": None,
  "PropertyTypeFilter": [],
  "PrimaryPropertyTypeFilter": [],
  "TransactionSearchFilters": {
    "CondoConversions": None,
    "Redevelopment": None,
    "ToBeDemolished": None,
    "Conversion": None,
    "Occupancy": None,
    "Renovation": None,
    "PendingTransactions": False,
    "ClosedTransactions": False,
    "TerminatedTransactions": False,
    "TypeSale": False,
    "TypeRefinancing": False,
    "TypeTransfer": False,
    "TypeConstruction": False,
    "IndividualProperty": False,
    "Portfolio": False,
    "EntityLevel": False,
    "FullLongTerm": None,
    "FullShortTerm": None,
    "PartialLeaseback": None,
    "MinorityInterest": None,
    "MajorityInterest": None,
    "DateRange": {
      "StartDate": "2024-03-07",
      "EndDate": "2025-03-07",
      "DateRangeType": 14
    },
    "PreviousDateRange": None,
    "MinPrice": None,
    "MaxPrice": None,
    "MinPPU": None,
    "MaxPPU": None,
    "MinCapRate": None,
    "MaxCapRate": None,
    "ForwardSale": None,
    "ResolvedDistress": None,
    "TopBuyersDateRange": None,
    "TopSellersDateRange": None,
    "ConstructionDateRange": {
      "StartDate": None,
      "EndDate": None,
      "DateRangeType": None
    },
    "ExcludeNAPrices": None
  },
  "CapitalGroupFilters": {
    "CapitalRole": "buyers",
    "CapitalSourceTypes": [],
    "CBGeographyInclude": [],
    "CBGeographyExclude": [],
    "JvSearchType": None
  },
  "InvestorGroupFilters": [],
  "PropertyDetailsFilter": {
    "YearBuiltMin": None,
    "YearBuiltMax": None,
    "YearRenovatedMin": None,
    "YearRenovatedMax": None,
    "UnitsMin": None,
    "UnitsMax": None,
    "FloorsMin": None,
    "FloorsMax": None,
    "Breeam": False,
    "Leed": False,
    "EnergyStar": False,
    "TenantNames": [],
    "CondoInterest": False,
    "LeasedFee": False,
    "LeaseHold": False,
    "OwnershipFee": False,
    "SingleTenant": False,
    "MultiTenant": False,
    "QScoreMin": 0,
    "QScoreMax": 100,
    "WalkScoreMin": 0,
    "WalkScoreMax": 100,
    "TransitScoreMin": 0,
    "TransitScoreMax": 100,
    "OccupancyMin": None,
    "OccupancyMax": None,
    "MixedUse": None,
    "ConstructionStatus": None,
    "HoldTimeMin": None,
    "HoldTimeMax": None,
    "OpportunityZone": None
  },
  "GreenRatingCategoryFilters": [],
  "RolesQueryWordFilters": [],
  "KeywordQueryWordFilters": [],
  "IncludeGeographyFilterItems": [],
  "ExcludeGeographyFilterItems": [],
  "CompanyIncludeGeographyFilterItems": [],
  "CompanyExcludeGeographyFilterItems": [],
  "CompanyPortfolioSizeSearchFilters": {
    "PropertyType": None,
    "UnitsMin": None,
    "UnitsMax": None,
    "SquareFootMin": None,
    "SquareFootMax": None,
    "PropertiesMin": None,
    "PropertiesMax": None,
    "TotalEstValueMin": None,
    "TotalEstValueMax": None
  },
  "CurrencyId": 1,
  "MeasurementUnitId": 1,
  "DateFormat": "MM/DD/YYYY",
  "HotelFilters": {
    "hotelFranchises": []
  },
  "LoanFilters": {
    "LoanAmountMin": None,
    "LoanAmountMax": None,
    "LoanTypes": [],
    "SyntheticLoanStatuses": [],
    "LoanPaymentStatuses": {
      "Day30": None,
      "Day60": None,
      "Day90": None,
      "Day120": None
    },
    "OriginationDateRange": {
      "StartDate": None,
      "EndDate": None,
      "DateRangeType": None
    },
    "DefeasanceDateRange": {
      "StartDate": None,
      "EndDate": None,
      "DateRangeType": None
    },
    "PrepayDateRange": {
      "StartDate": None,
      "EndDate": None,
      "DateRangeType": None
    },
    "DistressDateRange": {
      "StartDate": None,
      "EndDate": None,
      "DateRangeType": None
    },
    "MaturityDateRange": {
      "StartDate": None,
      "EndDate": None,
      "DateRangeType": None
    },
    "LenderGroups": [],
    "InterestRateTypes": [],
    "InterestRateMin": None,
    "InterestRateMax": None,
    "LikelyRefi": False,
    "ServicerNotesInclude": [],
    "ServicerNotesExclude": [],
    "Resolved": False
  },
  "ClimateFilter": {
    "AggregateRiskMin": None,
    "AggregateRiskMax": None,
    "OverallPhysicalRiskMin": None,
    "OverallPhysicalRiskMax": None,
    "CoastalFloodingMin": None,
    "CoastalFloodingMax": None,
    "FluvialFloodingMin": None,
    "FluvialFloodingMax": None,
    "TropicalCyclonesMin": None,
    "TropicalCyclonesMax": None,
    "ExtremeHeatMin": None,
    "ExtremeHeatMax": None,
    "ExtremeColdMin": None,
    "ExtremeColdMax": None,
    "WildfireMin": None,
    "WildfireMax": None
  },
  "PropertiesRequestType": 1,
  "Size": 500
}

from datetime import datetime, timedelta
import json
current_date = datetime.strptime("2024-03-07", "%Y-%m-%d")
end_date = datetime.strptime("2025-03-07", "%Y-%m-%d")
data_f = []
while current_date < end_date:
    next_period = current_date + timedelta(days=5)
    if next_period > end_date:
        next_period = end_date
    
    payload["TransactionSearchFilters"]["DateRange"]["StartDate"] = current_date.strftime("%Y-%m-%d")
    payload["TransactionSearchFilters"]["DateRange"]["EndDate"] = next_period.strftime("%Y-%m-%d")
    
    payload_js = json.dumps(payload, indent=2)
    headers = {
      'accept': 'application/json, text/plain, */*',
      'accept-language': 'en-US,en;q=0.9',
      'content-type': 'application/json;charset=UTF-8',
      'origin': 'https://app.rcanalytics.com',
      'priority': 'u=1, i',
      'referer': 'https://app.rcanalytics.com/transactions?lat=0&lon=0&zoom=2&view=fulltable&ne=109.3359375,73.92246884621464&sw=-109.3359375,-73.92246884621464',
      'sec-ch-ua': '"Not(A:Brand";v="99", "Google Chrome";v="133", "Chromium";v="133"',
      'sec-ch-ua-mobile': '?0',
      'sec-ch-ua-platform': '"Windows"',
      'sec-fetch-dest': 'empty',
      'sec-fetch-mode': 'cors',
      'sec-fetch-site': 'same-origin',
      'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36',
      'Cookie': '_ga=GA1.2.1453816737.1741360862; _gid=GA1.2.951863000.1741360862; _legacy_auth0.dylBYqw5EzveSNFsMBGpluStVK8wakYh.is.authenticated=True; auth0.dylBYqw5EzveSNFsMBGpluStVK8wakYh.is.authenticated=True; rca-da=59a01f90-2dbf-4dad-acc4-dea2f073b043; GCLB=CLbx1vfxw66EKBAD; rcajwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50VXNlcl9pZCI6MTUxNTAzLCJhY2NvdW50X2lkIjoyNTQ5OSwiZmlyc3ROYW1lX3R4IjoiUm9iZXJ0IiwibGFzdE5hbWVfdHgiOiJNYWdlZSIsImFjY291bnRBZG1pbl9mZyI6MSwic3lzdGVtQWRtaW5fZmciOjAsImxlZ2FjeVBhc3NLZXkiOiJFQ2NZeUFCb0dvK211bDRPMjRpSitnJCQiLCJydWxlcyI6W10sInNjb3BlIjpbIlBUUyIsIkxvYW4iLCJMb2FuRmVhdHVyZSIsIklVIiwiVFQiLCJUcmFja2VyIiwiVXNlclBhc3N3b3JkQ29udHJvbCIsIkRldmljZUF1dGgiLCJUVF9zYWxlcyIsIlRUX2NvbnN0cnVjdGlvbiIsIlRUX2xvYW5zIiwiUHJvcGVydHlTdXJ2ZWlsbGFuY2UiLCJNTUEiXSwiemlwQ29uZmlybWVkX2ZnIjp0cnVlLCJkZXZpY2VBdXRoQ29uZmlybWVkX2ZnIjp0cnVlLCJleGNlbEV4cG9ydFJvd3MiOm51bGwsImxvZ2luQWxsb3dlZF9mZyI6MSwibW9iaWxlTG9naW5Pbmx5X2ZnIjowLCJlbWFpbCI6ImJvYmJ5QG1sc2F2ZW50dXJlcy5jb20iLCJhdXRoU2Vzc2lvbklkIjoiZTk1MTJmZjAtZmI2Ny0xMWVmLWJkNjMtODU0YWYwMTFiN2E4Iiwic2Vzc2lvbklkIjoiYjFlNWQyYzYtYjM3Mi00ZWU0LTkwMTctNTc1NDVlNGNkYzEwIiwibGRIYXNoIjoiMDA3ODRjNTAwYjk5YTg4ZWI0Yjc4ODJiNzNkMWFjYzdjNDNkNTk4YTBiZTQ3OWMwY2IxNmU4YmE2YzllYmEwNCIsImV4cCI6MTc0MTQ1MjYxMiwiaWF0IjoxNzQxMzYwOTE4fQ.KLqcbM2KTH3dqaxbCJaFyJKqG3EEhNfT6CZCty35VCI; rcajwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50VXNlcl9pZCI6MTUxNTAzLCJhY2NvdW50X2lkIjoyNTQ5OSwiZmlyc3ROYW1lX3R4IjoiUm9iZXJ0IiwibGFzdE5hbWVfdHgiOiJNYWdlZSIsImFjY291bnRBZG1pbl9mZyI6MSwic3lzdGVtQWRtaW5fZmciOjAsImxlZ2FjeVBhc3NLZXkiOiJFQ2NZeUFCb0dvK211bDRPMjRpSitnJCQiLCJydWxlcyI6W10sInNjb3BlIjpbIlBUUyIsIkxvYW4iLCJMb2FuRmVhdHVyZSIsIklVIiwiVFQiLCJUcmFja2VyIiwiVXNlclBhc3N3b3JkQ29udHJvbCIsIkRldmljZUF1dGgiLCJUVF9zYWxlcyIsIlRUX2NvbnN0cnVjdGlvbiIsIlRUX2xvYW5zIiwiUHJvcGVydHlTdXJ2ZWlsbGFuY2UiLCJNTUEiXSwiemlwQ29uZmlybWVkX2ZnIjp0cnVlLCJkZXZpY2VBdXRoQ29uZmlybWVkX2ZnIjp0cnVlLCJleGNlbEV4cG9ydFJvd3MiOm51bGwsImxvZ2luQWxsb3dlZF9mZyI6MSwibW9iaWxlTG9naW5Pbmx5X2ZnIjowLCJlbWFpbCI6ImJvYmJ5QG1sc2F2ZW50dXJlcy5jb20iLCJhdXRoU2Vzc2lvbklkIjoiZTk1MTJmZjAtZmI2Ny0xMWVmLWJkNjMtODU0YWYwMTFiN2E4Iiwic2Vzc2lvbklkIjoiYjFlNWQyYzYtYjM3Mi00ZWU0LTkwMTctNTc1NDVlNGNkYzEwIiwibGRIYXNoIjoiMDA3ODRjNTAwYjk5YTg4ZWI0Yjc4ODJiNzNkMWFjYzdjNDNkNTk4YTBiZTQ3OWMwY2IxNmU4YmE2YzllYmEwNCIsImV4cCI6MTc0MTQ1MjkyNSwiaWF0IjoxNzQxMzYwOTE4fQ.g2x5ijUUcyEppxqxVQk8_YwDticeKWVaTLcBhef2kUQ'
    }
    
    response = requests.request("POST", url, headers=headers, data=payload_js)
    
    data = json.loads(response.text)
    data_f.extend(data["data"]["pinTransactionItems"])
    print(len(data_f),current_date.strftime("%Y-%m-%d"),next_period.strftime("%Y-%m-%d"))
    current_date = next_period
    
data_ff =[]
for i in data_f:
    if i not in data_ff:
        data_ff.append(i)


df = pd.DataFrame(data_ff)

df.to_csv("Transactions.csv")